server:
  port: 8092
spring:
  application:
    name: assurance-service
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 30000
    username: guest
    password: guest
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG
