server:
  port: 8080
spring:
  application:
    name: risk-service
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 30000
    username: guest
    password: guest
balance-service:
  ribbon:
    listOfServers: localhost:8081
agency-service:
  ribbon:
    listOfServers: localhost:8091
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG