server:
  port: 8081
spring:
  application:
    name: balance-service
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 30000
    username: guest
    password: guest
assurance-service:
  ribbon:
    listOfServers: localhost:8092
salesdata-service:
  ribbon:
    listOfServers: localhost:8093
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
