server:
  port: 8091
spring:
  application:
    name: agency-service
  sleuth:
    sampler:
      percentage: 1.0
  rabbitmq:
    host: localhost
    port: 30000
    username: guest
    password: guest
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:                           
    platform: h2                       
    schema: classpath:schema.sql       
    data: classpath:data.sql            
#  zipkin:
#    base-url: http://localhost:9411
#  sleuth:
#    sampler:
#      percentage: 1.0
logging:
  level:
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO
    org.hibernate.type.descriptor.sql.BasicExtractor: INFO
    
## INFO
